# Submenus require a new version of MkDocs:
# pip install https://github.com/mkdocs/mkdocs/archive/master.zip
# Reference: https://github.com/mkdocs/mkdocs/issues/6

site_name: Spork Docs 4.0
site_description: Documentation for Spork 4.0
site_author: Ken Van Hoeylandt
site_favicon: images/sporklogosmall.png
site_url: http://spork.bytewelder.com
repo_url: https://github.com/ByteWelder/Spork
docs_dir: src
site_dir: ../docs/docs/4.0
theme: mkdocs
extra_css:
  - css/extra.css
markdown_extensions:
  - markdown.extensions.fenced_code
pages:
  - 'Home': index.md
  - 'Spork Core':
      - 'Introduction': 'spork-core/introduction.md'
      - 'Creating Annotations': 'spork-core/creating-annotations.md'
  - 'Spork Inject':
    - 'Introduction': 'spork-inject/introduction.md'
    - 'User Guide': 'spork-inject/user-guide.md'
    - 'Migrating from Dagger': 'spork-inject/migrating-from-dagger.md'
  - 'Spork Android':
    - 'Introduction': 'spork-android/introduction.md'
    - 'Annotations':
      - '@BindClick': 'spork-android/annotations/bindclick.md'
      - '@BindFragment': 'spork-android/annotations/bindfragment.md'
      - '@BindLayout': 'spork-android/annotations/bindlayout.md'
      - '@BindResource': 'spork-android/annotations/bindresource.md'
      - '@BindView': 'spork-android/annotations/bindview.md'
    - 'Examples':
      - 'Application': 'spork-android/examples/application.md'
      - 'Activity': 'spork-android/examples/activity.md'
      - 'ContentProvider': 'spork-android/examples/contentprovider.md'
      - 'Fragment': 'spork-android/examples/fragment.md'
      - 'RecyclerView': 'spork-android/examples/recyclerview.md'
      - 'Service': 'spork-android/examples/service.md'
      - 'View': 'spork-android/examples/view.md'
      - 'ProGuard': 'spork-android/proguard.md'


