# Submenus require a new version of MkDocs:
# pip install https://github.com/mkdocs/mkdocs/archive/master.zip
# Reference: https://github.com/mkdocs/mkdocs/issues/6

site_name: Spork Library
site_description: Spork is an annotation binding library
site_author: Ken Van Hoeylandt
site_favicon: images/sporklogosmall.png
site_url: https://sporklibrary.github.io
repo_url: https://github.com/sporklibrary
theme: mkdocs
extra_css:
  - css/extra.css
site_dir: site
markdown_extensions:
  - markdown.extensions.fenced_code
google_analytics: ['UA-78126960-1', 'sporklibrary.github.io']
pages:
  - Introduction: index.md
  - 'Android Guide':
    - 'Annotations':
      - '@BindClick': 'documentation/android/annotations/bindclick.md'
      - '@BindFragment': 'documentation/android/annotations/bindfragment.md'
      - '@BindLayout': 'documentation/android/annotations/bindlayout.md'
      - '@BindResource': 'documentation/android/annotations/bindresource.md'
      - '@BindView': 'documentation/android/annotations/bindview.md'
      - '@Inject': 'documentation/java/annotations/inject.md'
    - 'Examples':
      - 'Application': 'documentation/android/examples/application.md'
      - 'Activity': 'documentation/android/examples/activity.md'
      - 'Inject': 'documentation/java/examples/inject.md'
      - 'ContentProvider': 'documentation/android/examples/contentprovider.md'
      - 'Fragment': 'documentation/android/examples/fragment.md'
      - 'RecyclerView': 'documentation/android/examples/recyclerview.md'
      - 'Service': 'documentation/android/examples/service.md'
      - 'View': 'documentation/android/examples/view.md'
    - 'Advanced Topics':
      - 'Creating Annotations': 'documentation/java/advanced/creating-annotations.md'
      - 'ProGuard': 'documentation/android/advanced/proguard.md'
      - 'Binding order': 'documentation/java/advanced/binding-order.md'
  - 'Java Guide':
    - 'Annotations':
      - '@Inject': 'documentation/java/annotations/inject.md'
    - 'Examples':
      - 'Inject': 'documentation/java/examples/inject.md'
    - 'Advanced Topics':
      - 'Creating Annotations': 'documentation/java/advanced/creating-annotations.md'
      - 'Binding order': 'documentation/java/advanced/binding-order.md'
  - About:
    - Benchmarks: about/benchmarks.md
    - Comparison: about/comparison.md 
    - License: about/license.md
    - Release Notes: 'about/release-notes.md'
