site_name: Spork
site_description: Spork is an annotation binding library
site_author: Ken Van Hoeylandt
site_favicon: images/sporklogosmall.png
site_url: http://spork.bytewelder.com
repo_url: https://github.com/ByteWelder/Spork
docs_dir: 'src'
site_dir: '../docs'
theme: spacelab  # pip install mkdocs-bootswatch --user
extra_css:
  - css/extra.css
markdown_extensions:
  - markdown.extensions.fenced_code
google_analytics: ['UA-78126960-1', 'spork.bytewelder.com']
pages:
  - Introduction: index.md
  - Documentation: documentation.md
  - About:
    - Benchmarks: about/benchmarks.md
    - Comparison: about/comparison.md 
    - License: about/license.md
    - Release Notes: 'about/release-notes.md'
